aluno/urls.py
from django.urls import path
from . import views 

app_name = 'aluno'

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastro', views.cadastrar, name='cadastrar'),
]

instrutor/urls.py
from django.urls import path
from . import views 

app_name = 'instrutor'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='escola.html')),

    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno') ),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tiposdeatividade/urls.py
from django.urls import path
from . import views

app_name = 'tiposdeatividade'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
]

titulo/urls.py
from django.urls import path
from . import views 

app_name = 'titulo'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('lista/', views.listar, name='listar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_titulo"),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name="carregar_titulo"),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

turma/urls.py
from django.urls import path
from . import views 

app_name = 'turma'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
    path('registrar_ausencia', views.registrar_ausencia, name='registrar_ausencia'),
]

utilitarios/urls.py
from django.urls import path
from . import views 

app_name = 'utilitarios'

urlpatterns = [
    path('contato/', views.carregar_contato, name="contato"),
    path('carga/', views.popular_bd, name='popular'),
]

utilitarios/models.py
from django.db import models

# Create your models here.

utilitarios/views.py
from django.shortcuts import render, redirect

from utilitarios import utils

# Create your views here.
def carregar_contato(request):
    return render(request, 'utilitarios/contato.html')

def popular_bd(request):
    utils.truncar_tabelas()
    utils.popular_tiposdeatividade()
    utils.popular_titulo()
    utils.popular_aluno()
    #utils.popular_instrutor()
    utils.popular_turma()

    return redirect('/')


utilitarios/templates/utilitarios/contato.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'tiposdeatividade:cadastrar'%}" class="nav-link">Tipos de Atividade</a>
            <a href="{% url 'titulo:cadastrar' %}" class="nav-link">Títulos</a>
            <a href="{% url 'aluno:cadastrar' %}" class="nav-link">Alunos</a>
            <a href="{% url 'instrutor:cadastrar' %}" class="nav-link">Instrutor</a>
            <a href="{% url 'turma:cadastrar' %}" class="nav-link">Turmas</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 w-75 mx-auto minha-fonte">
        
        <div class= "row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-0 my-h2">Fale conosco</h2>
            </div>                    
        </div>

        <form name="frmContato" id="idFrmContato" action="#" method="POST" class="my-label-color-purple">

            <div class="form-row mt-4">
                    <div class="form-group col-md-6">
                        <label for="idNome">Nome</label>
                        <input class="form-control" type="text" name="nome" id="idNome" maxlength="70" placeholder="Informe o seu Nome" required>
                    </div>
                
                    <div class="form-group col-md-6">
                            <label for="idUltimoNome">Último Nome</label>
                            <input class="form-control" type="text" name="ultimoNome" id="idUltimoNome" maxlength="70" placeholder="Informe o seu último Nome" required>
                    </div>
            </div>

            <div class="form-group">
                <label for="idEmail">E-mail</label>
                <input class="form-control" type="email" name="email" id="idEmail" maxlength="100" placeholder="Informe o seu E-mail" required>
            </div>          
            
            <div class="form-group">
                <label for="idTelefone">Telefone</label>
                <input class="form-control" type="tel" name="telefone" id="idTelefone" placeholder="Informe o seu Telefone"  
                       pattern="(\(?[0-9]{2}\)?\s)?([0-9]{4}\-[0-9]{4})" required>
            </div>

            <fildset class="form-group">

                <div class="row">
                    <legend class="col-form-label pt-0 col-md-2">Gênero</legend>

                    <div class="col-md-10">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="genero" value="F" id="idGeneroF">
                            <label class="form-check-label" for="idGeneroF">Feminino</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="genero" value="M" id="idGeneroF">
                            <label class="form-check-label" for="idGeneroM">Masculino</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="genero" value="O" id="idGeneroO">
                            <label class="form-check-label" for="idGeneroO">Outros</label>
                        </div>
                    </div>    
                </div>
            </fildset>

            <div class="form-group">
                <label for="idAssunto">Assunto</label>
                <select class="form-control" name="assunto" id="idAssunto" required>
                    <option value="0" selected>Selecione...</option>
                    <option value="E">Elogio</option>
                    <option value="C">Crítica</option>
                    <option value="S">Solicitação</option>
                    <option value="O">Outros</option>
                </select>
            </div>
            
            <div class="form-group">
                <label for="idMensagem">Mensagem</label>
                <textarea class="form-control" rows="10" col="200" id="idMensagem" name="mensagem" class="myTextArea" placeholder="Preencha com a mensagem desejada" required></textarea>
            </div>

            <div class="form-group text-center">
                <input type="reset" value="Limpar"  class="btn btn-primary btn-md">
                <input type="submit" value="Enviar" class="btn btn-primary btn-md">
            </div>
        </form>
    </main>
    {% endblock %}