aluno/urls.py
from django.urls import path
from . import views 

app_name = 'aluno'

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastro', views.cadastrar, name='cadastrar'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='escola.html')),

    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno') ),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

titulo/urls.py
from django.urls import path
from . import views 

app_name = 'titulo'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('lista/', views.listar, name='listar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_titulo"),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name="carregar_titulo"),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

titulo/models.py
from django.db import models

# Create your models here.
class Titulo(models.Model):
    codigo = models.AutoField(primary_key=True,
                              help_text='Código do Título')
    descricao = models.CharField(max_length=100,
                                 help_text='Informe a descrição do Título')
    
    def __str__(self):
        return f'{self.codigo} - {self.descricao}'
    

titulo/forms.py
from django import forms

# classe formulario inclusao
class TituloForm(forms.Form):
    descricao = forms.CharField(max_length=100,
                                required=True,
                                help_text='Informe a descrição do Título')
    
class TituloAtualizarForm(forms.Form):
    codigo = forms.IntegerField(required=True,
                              help_text='Informe o código do Título')
    descricao = forms.CharField(max_length=100,
                            required=True,
                            help_text='Informe a descrição do Título')

titulo/views.py
from django.shortcuts import render, redirect

from titulo.models import Titulo
from titulo.forms import TituloForm, TituloAtualizarForm
from instrutor.models import Instrutor


# Create your views here.
def listar(request):

    lista_titulos = Titulo.objects.all()
    contexto = {
        'titulos': lista_titulos
    }

    return render(request, 'titulo/listarTitulos.html', context=contexto)


# carregar a pagina para cadastrar um titulo na base de dados
def cadastro(request):
    return render(request, 'titulo/cadastroTitulos.html')


# acao de cadastrar um titulo na base de dados
def cadastrar(request):
    form = TituloForm(request.POST)
    if form.is_valid():
        dados_titulo = form.cleaned_data
        titulo = Titulo(
            descricao = dados_titulo['descricao']
        )
        titulo.save()

    return render(request, 'titulo/cadastroTitulos.html')


# excluir um titulo
def excluir(request, codigo):
    titulo = Titulo.objects.get(pk=codigo)

    # verifica se ha um instrutor relacionado ao tiutlo a excluir
    # caso contrario, o titulo poderá ser excluido
    instrutores = Instrutor.objects.filter(codigo_titulo=codigo)
    if not instrutores:
        titulo.delete()

    return redirect('titulo:listar')

# carregar titulo para atualizar
def carregar_titulo(request, codigo):
    # obter titulo a atualizar basead no codigo informado
    titulo = Titulo.objects.get(pk=codigo)
    contexto = {
        'titulo': titulo,
    }

    return render(request, 'titulo/atualizarTitulo.html', context=contexto)

# atualizar a base de dados para o titulo selecionado
def atualizar(request):
    if request.method == 'POST':
        form = TituloAtualizarForm(request.POST)
        if form.is_valid():

            dados_titulo = form.cleaned_data

            codigo = dados_titulo['codigo']

            titulo = Titulo.objects.get(pk=codigo)
            titulo.descricao = dados_titulo['descricao']

            titulo.save()
        
        # imprimir no console mensagens de erro na validação do formulário
        #else:
        #    print(form.errors)

    return redirect('titulo:listar')

titulo/templates/titulo/atualizarTitulo.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'titulo:cadastro' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'titulo:listar' %}" class="nav-link">Listar</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <!-- main -->
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Atualização de Título</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="TituloAtualizarForm" action="{% url 'titulo:atualizar_titulo' %}" method="post" class="my-label-color-purple">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="idCodigo" class="col-form-label">Código</label>
                <input class="form-control" type="text" id="idCodigo" name="codigo" value="{{ titulo.codigo }}" readonly>  
            </div>

            <div class="form-group">
                <label for="idDescricao">Descrição</label>
                <input class="form-control" type="text" id="idDescricao" name="descricao" value="{{ titulo.descricao }}" maxlength="70" required> 
            </div>
            
            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Atualizar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
{% endblock %}

titulo/templates/titulo/cadastroTitulos.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'titulo:cadastro' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'titulo:listar' %}" class="nav-link">Listar</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Títulos</h2>
            </div>
        </div>

        <form action="{% url 'titulo:cadastrar' %}" method="POST" name="frmCadastrarTitulo" id="idFrmCadastrarTiposAtividade">
            {% csrf_token %}
            
            <div class="form-group">
                <label for='idDescricao'>Descrição</label>
                <input class="form-control" type='text' id='idDescricao' name='descricao' placeholder='Informe a descrição' required>
            </div>
            <div class='form-group text-center'>
                <input type='reset'  value='Limpar' class='btn btn-primary btn-md'>
                <input type='submit' value='Cadastrar' class='btn btn-primary btn-md' id="btnCadastrarTiposAtividade">
            </div>
        </form>
    </main>
{% endblock %}    

titulo/templates/titulo/listarTitulos.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'titulo:cadastro' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'titulo:listar' %}" class="nav-link">Listar</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Lista de Títulos</h2>
            </div>
        </div>

        {% if titulos %}

        <!-- tabela responsiva -->
            <div class="table-responsive">

                <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
                <table class="table
                            table-borderless
                            text-center
                            my-table-hover
                            my-table-image
                            my-table-td-first-child
                            my-table-border-bottom
                            my-table-th
                            w-100">

                    <!-- cabecalho -->
                    <thead>
                        <!-- linhas -->
                        <tr>
                            <!-- colunas cabecalho -->
                            <th>Código</th>
                            <th>Descrição</th>
                            <th>Ações</th>
                        </tr>
                    </thead>

                    <!-- linhas -->
                    {% for titulo in titulos %}
                        <tr>
                            <td class="text-center"> {{ titulo.codigo }} </td>
                            <td class="text-left"> {{ titulo.descricao }} </td>
                            <td>
                                <a href="{% url 'titulo:carregar_titulo' titulo.codigo %}" class="btn btn-mini"><i class="far fa-edit"></i></a>
                                <button type="button" class="btn" role="button" data-target="#modalExcluirTitulo"
                                        data-toggle="modal"  
                                        data-descricao="{{ titulo.descricao }}" 
                                        data-url="{% url 'titulo:excluir_titulo' titulo.codigo %}">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                            </td>
                        </tr>
                    {% endfor %}

                </table>

            </div>

        {% else %}

            <div class='text-danger'>
                <p>Não há títulos cadastrados</p>
            </div>

        {% endif %}

    </main>

    <!-- Modais -->
    <div class="modal fade" id="modalExcluirTitulo" role="dialog" aria-labelledby="Confirmação" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalLabel">Confirmação</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p id="mensagemExclusao"></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Cancelar</button>
                    <button type="button" class="btn btn-primary" id="btnExcluir">Excluir</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block javascript_complementar %}
    <!-- Prepara o modal com os dados da imagem do Titulo a ser excluido -->
    <script type="text/javascript">
        $(document).ready(function() {
            $('#modalExcluirTitulo').on('show.bs.modal', function(event) {
                var descricao = $(event.relatedTarget).data('descricao');
                var urlExcluir = $(event.relatedTarget).data('url');
                $("#mensagemExclusao").text("Título [ " + descricao + "  ]?");

                $.fn.excluirTitulo = function() {
                    var url = $(event.relatedTarget).data('url');
                    location.replace(url);
                }
            });
        
            $("#btnExcluir").on('click', function() {
                $.fn.excluirTitulo();
                return false;
            });            
        });
    </script>
{% endblock %}
