aluno/urls.py
from django.urls import path
from . import views 

app_name = 'aluno'

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastro', views.cadastrar, name='cadastrar'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='escola.html')),

    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno') ),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

turma/urls.py
from django.urls import path
from . import views 

app_name = 'turma'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
    path('registrar_ausencia', views.registrar_ausencia, name='registrar_ausencia'),
]

turma/models.py
from django.db import models
from django.utils import timezone

from tiposdeatividade.models import TiposDeAtividade
from aluno.models import Aluno
from instrutor.models import Instrutor

# Create your models here.
class Turma(models.Model):
    numero = models.AutoField(primary_key=True,
                                  help_text='Matrícula do Aluno')
    horario_aula = models.TimeField(help_text='Informe a hora de início da Turma')
    
    duracao_aula = models.SmallIntegerField(help_text='Informe a duração em horas da Turma')

    data_inicial = models.DateField(null=False,
                                    default=timezone.now(), 
                                    help_text='Informe a data inicial da Turma')

    data_final = models.DateField(null=True,
                                  blank=True,
                                  help_text='Informe a data final da Turma')
    
    codigo_atividade = models.ForeignKey(TiposDeAtividade, 
                                         null=True, blank=True, on_delete=models.CASCADE,
                                         related_name='atividades')
    
    matricula_monitor = models.ForeignKey(Aluno, null=True, blank=True, 
                                          on_delete=models.SET_NULL,
                                          related_name='alunos')
    
    id_instrutor = models.ForeignKey(Instrutor, null=True, blank=True, on_delete=models.CASCADE,
                                     related_name='instrutores')
    

    def __str__(self):
        return f'{self.numero}'

turma/views.py
from django.shortcuts import render

# Create your views here.
def cadastrar(request):
    return render(request, 'turma/cadastroTurma.html')

def listar(request):
    return render(request, 'turma/listarTurmas.html')

def registrar_ausencia(request):
    return render(request, 'turma/registroAusencia.html')


turma/templates/turma/cadastroTurma.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'turma:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'turma:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'turma:registrar_ausencia' %}" class="nav-link">Registrar Ausência</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Cadastro de Turmas</h2>
            </div>
        </div>

        <!-- formulario HTML -->
        <form name="frmCadastrarTurma" action="#" method="post" class="my-label-color-purple">

            <div class="form-group">
                <label for="idHorarioAula" class="col-form-label">Horário da Aula</label>
                <input class="form-control" type="time" id="idHorarioAula" name="horarioAula" required>
            </div>

            <div class="form-group">
                <label for='idDuracaoAula'>Duração da Aula em horas</label>
                <input class="form-control" type='number' id='idDuracaoAula' name='duracaoAula' required>
            </div>

            <div class="form-group">
                <label for='idDataInicial'>Data de Início</label>
                <input class="form-control" type='date' id='idDataInicial' name='dataInicial' required>
            </div>

            <!-- montagem do combo com os tipos de atividade -->
            <div class="form-group">
                <label for="idTipoAtividade">Tipo de Atividade</label>
                <select class="form-control" id="idTipoAtividade" name="tipoAtividade">
                    <option value="0">Selecione...</option>
                    <option value="1">Programador Web</option>
                    <option value="2">Técnico em Informática</option>
                    <option value="3">Web Designer</option>
                    <option value="4">Educação Física</option>

                </select>
            </div>


            <!-- montagem do combo com os instrutores -->
            <div class="form-group">
                <label for="idInstrutor">Instrutor</label>
                <select class="form-control" id="idInstrutor" name="idInstrutor">
                    <option value="0">Selecione...</option>
                    <option value="2">Maria Joaquina</option>
                    <option value="3">Juliana Fergusson</option>
                </select>
            </div>

            <!-- montagem do combo com os alunos -->
            <div class="form-group">
                <label for="idAluno">Aluno Monitor</label>
                <select class="form-control" id="idAluno" name="matriculaAlunoMonitor">
                    <option value="0">Selecione...</option>
                    <option value="1">Marcos Ferreira</option>
                    <option value="2">José Mauro</option>
                    <option value="3">Hian Ferreira</option>
                    <option value="4">Pedro Miranda</option>
                    <option value="5">Stephanie Negri</option>
                    <option value="6">Carlos Alexandre</option>
                    <option value="7">Felipe Gomes</option>
                </select>
            </div>

            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Cadastrar" class="btn btn-primary btn-md">
            </div>

        </form>

    </main>
{% endblock %}

turma/templates/turma/listarTurmas.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'turma:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'turma:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'turma:registrar_ausencia' %}" class="nav-link">Registrar Ausência</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Lista de Turmas</h2>
            </div>
        </div>

        <!-- tabela responsiva -->
        <div class="table-responsive">

            <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
            <table class="table
                        table-borderless
                        text-center
                        my-table-hover
                        my-table-image
                        my-table-td-first-child
                        my-table-border-bottom
                        my-table-th
                        w-100">

                <!-- cabecalho -->
                <thead>
                    <!-- linhas -->
                    <tr>
                        <!-- colunas cabecalho -->
                        <th>Número</th>
                        <th>Horário da Aula</th>
                        <th>Duração da Aula</th>
                        <th>Data Inicial</th>
                        <th>Data Final</th>
                        <th>Atividade</th>
                        <th>Instrutor</th>
                        <th>Titularidade</th>
                        <th>Aluno Monitor</th>
                    </tr>
                </thead>

                <!-- linhas -->
                <tbody>
                    <tr>
                        <td> 1 </td>
                        <td> 10:00:00 </td>
                        <td> 2 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> Marcos Ferreira </td>
                    </tr>
                    <tr>
                        <td> 2 </td>
                        <td> 13:00:00 </td>
                        <td> 4 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> José Mauro </td>
                    </tr>
                    <tr>
                        <td> 3 </td>
                        <td> 18:00:00 </td>
                        <td> 4 </td>
                        <td> 01/03/2022 </td>
                        <td> -- </td>
                        <td> Programador Web </td>
                        <td> Jefferson Gonçalves </td>
                        <td> Professor Doutor </td>
                        <td> Hian Ferreira </td>
                    </tr>
                </tbody>
            </table>

        </div>

    </main>
{% endblock %}

turma/templates/turma/registroAusencia.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'turma:cadastrar' %}" class="nav-link">Cadastrar</a>
            <a href="{% url 'turma:listar' %}" class="nav-link">Listar</a>
            <a href="{% url 'turma:registrar_ausencia' %}" class="nav-link">Registrar Ausência</a>
        </div>
    </div>
{% endblock %}

{% block corpo %}
    <main class="container m-2 w-75 mx-auto my-font-family">

        <div class="row">
            <div class="col text-center m-0">
                <h2 class="mt-2 mb-5 my-h2">Registro de Ausências</h2>
            </div>
        </div>

        <!-- formulario para escolher a turma -->
        <form name="frmDefinirTurma" id="idFrmDefinirTurma" action="#" method="post" class="my-label-color-purple">

            <!-- montagem do combo com as turmas cadastradas que tenha aluno -->
            <div class="form-group">
                <label for="idTurma">Turma</label>
                <select class="form-control" id="idTurma" name="numeroTurma">
                    <option value="0">Selecione...</option>
                    <option value="1">Turma 0001 - 10:00:00</option>
                    <option value="2">Turma 0002 - 13:00:00</option>
                    <option value="3">Turma 0003 - 18:00:00</option>
                </select>
            </div>

            <div class="form-group my-4 text-center">
                <input type="button" value="Limpar" class="btn btn-primary btn-md" id="idLimparTurmas">
                <input type="submit" value="Consultar" class="btn btn-primary btn-md">
            </div>

        </form>

        <!-- formulario HTML para registrar ausencia de alunos de uma turma -->
        <form name="frmRegistrarAusencia" action="#" method="post" class="my-label-color-purple">

            <!-- utiliza um input "hidden" para armazerar a turma escolhida inicialmente -->
            <input type="hidden" name="numeroTurmaSelecionada" value="">

            <!-- montagem do combo com os tipos de atividade -->
            <div class="form-group">
                <label for="idAlunoTurma">Aluno da Turma</label>
                <select class="form-control" id="idAlunoTurma" name="matriculaAluno">
                    <option value="0">Selecione...</option>
                    <option value="1">Marcos Ferreira</option>
                    <option value="2">José Mauro</option>
                    <option value="3">Hian Ferreira</option>
                </select>
            </div>


            <div class="form-group">
                <label for="idDataAusencia" class="col-form-label">Data da Ausência</label>
                <input class="form-control" type="date" id="idDataAusencia" name="dataAusencia" required>
            </div>

            <div class="form-group my-4 text-center">
                <input type="reset" value="Limpar" class="btn btn-primary btn-md">
                <input type="submit" value="Registrar" class="btn btn-primary btn-md">
            </div>

        </form>
    </main>
{% endblock %}

{% block js %}
    <!-- acoes e validacoes sobre os formularios -->
        <script type="text/javascript">
        let vFrmDefinirTurma = document.querySelector('form[name="frmDefinirTurma"]');
        vFrmDefinirTurma.onsubmit = validarTurmaSelecionada;

        let btnIdLimparTurmas = document.getElementById("idLimparTurmas");
        btnIdLimparTurmas.onclick = limparFrmDefinirTurma;

        // verifica se o elemento do tipo formulario para a selecao de aluno esta no documento HTML
        // neste caso, permitir remove-lo quando o botao "Limpar" do formulario da turma for clicado
        if (document.querySelector('form[name="frmRegistrarAusencia"]')) {
            let vFrmRegistrarAusencia = document.querySelector('form[name="frmRegistrarAusencia"]');
            vFrmRegistrarAusencia.onsubmit = validarAlunoSelecionado;
        }

        // No formulario de selecao da turma, nao é permitido executar o submit para a opcao "Selecione" 
        function validarTurmaSelecionada() {
            let turmaSelecionada = document.getElementById('idTurma').value;
            if (parseInt(turmaSelecionada) == 0) {
                alert("Selecione uma Turma!");
                return false;
            }
        }

        // No formulario de selecao de aluno da turma, nao é permitido executar o submit para a opcao "Selecione" 
        function validarAlunoSelecionado() {
            let alunoSelecionado = document.getElementById('idAlunoTurma').value;
            if (parseInt(alunoSelecionado) == 0) {
                alert("Selecione uma dos alunos da Turma!");
                return false;
            }
        }

        // remove do HTML o elemento form onde sera informado o aluno que faltou e sua data
        // caso 
        function limparFrmDefinirTurma() {

            // procura o formulario FrmRegistrarAusencia e remove do HTML se existir
            if (document.querySelector('form[name="frmRegistrarAusencia"]')) {
                let vFrmRegistrarAusencia = document.querySelector('form[name="frmRegistrarAusencia"]');
                vFrmRegistrarAusencia.remove();
            }

            // retorna o valor original da caixa de selecao de Turma
            document.getElementById('idTurma').selectedIndex = 0;
        }
    </script>
{% endblock %}