aluno/urls.py
from django.urls import path
from . import views 

app_name = 'aluno'

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastro', views.cadastrar, name='cadastrar'),
]

instrutor/urls.py
from django.urls import path
from . import views 

app_name = 'instrutor'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='escola.html')),

    path('tiposdeatividade/', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno') ),
    path('instrutor/', include("instrutor.urls") ),
    path('titulo/', include("titulo.urls") ),
    path('turma/', include("turma.urls") ),
    path('utilitarios/', include("utilitarios.urls") ),
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

titulo/urls.py
from django.urls import path
from . import views 

app_name = 'titulo'

urlpatterns = [
    path('cadastro/', views.cadastro, name='cadastro'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('lista/', views.listar, name='listar'),
    path('excluir/<int:codigo>', views.excluir, name="excluir_titulo"),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name="carregar_titulo"),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

turma/urls.py
from django.urls import path
from . import views 

app_name = 'turma'

urlpatterns = [
    path('cadastro', views.cadastrar, name='cadastrar'),
    path('lista', views.listar, name='listar'),
    path('registrar_ausencia', views.registrar_ausencia, name='registrar_ausencia'),
]

utilitarios/urls.py
from django.urls import path
from . import views 

app_name = 'utilitarios'

urlpatterns = [
    path('contato/', views.carregar_contato, name="contato"),
    path('carga/', views.popular_bd, name='popular'),
]

templates/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    {% block title %}
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- define e insere um favicon no documento HTML -->
    <link href="{% static 'img/python.ico' %}" rel="shortcut icon">

    <!-- versao gratuita do Font Awesome icons-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <!-- insira este conteudo aqui que representa o CSS do Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Google  icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="{% static 'css/meu-estilo.css' %}" rel="stylesheet">
</head>

<body>

    <!-- seu codigo comeca aqui -->

    <!-- container bootstrap -->
    <header class="container px-0">

        <nav class="navbar navbar-expand-lg navbar-light bg-light px-0">

            <!-- logo -->
            <div>
                <a class="navbar-brand mx-auto">
                    <img src="{% static 'img/python_64.png' %}">
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynavbar"
                aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Navegação Alternativa">
                Menu <span class="navbar-toggler-icon"></span>
            </button>

            <!-- menu -->
            {% block menu %}
            {% endblock %}
            
        </nav>

        {% block titulo_pagina %}
        {% endblock %}
        
    </header>

    {% block corpo %}
    {% endblock %}

    <footer class="container text-center">
        <div class="row border-top border-primary bg-light">
            <div class="col font text-primary copyright">
                <p>&copy; Copyright Pmg Web</p>
            </div>
        </div>
    </footer>

    <!-- seu codigo termina aqui -->

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>

    {% block javascript_complementar %}
    {% endblock %}

</body>

</html>

templates/escola.html
{% extends "base_template.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
    <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
        <div class="navbar-nav">
            <a href="/" class="nav-link">Início</a>
            <a href="{% url 'tiposdeatividade:cadastrar'%}" class="nav-link">Tipos de Atividade</a>
            <a href="{% url 'titulo:cadastrar' %}" class="nav-link">Títulos</a>
            <a href="{% url 'aluno:cadastrar' %}" class="nav-link">Alunos</a>
            <a href="{% url 'instrutor:cadastrar' %}" class="nav-link">Instrutor</a>
            <a href="{% url 'turma:cadastrar' %}" class="nav-link">Turmas</a>
            <a href="{% url 'utilitarios:contato' %}" class="nav-link">Contato</a>
        </div>
    </div>
{% endblock %}

{% block titulo_pagina %}
    <div class="container text-center">
        <div class="jumbotron mt-5">
            <h1 class="display-4">Escola ABC do Saber</h1>
        </div>
    </div>
{% endblock %}


templates/index.html
<!DOCTYPE HTML>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0; url=escola.html">
</head>

<body>
</body>

</html>